name: release
on:
  workflow_dispatch: null
  release:
    types: [ published ]
jobs:
  galaxyrelease:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - name: update packages
        run: sudo apt-get update -y

      - name: install make
        run: sudo apt-get install -y build-essential

      - name: setup python 3
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # pin@v2
        with:
          python-version: '3.x'

      - name: build the package
        run: make build
        env:
          SPECDOC_VERSION: ${{ github.event.release.tag_name }}

      - name: publish the release to pypi
        uses: pypa/gh-action-pypi-publish@37f50c210e3d2f9450da2cd423303d6a14a6e29f # pin@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
